### ISSUE TITLE
Spotify doesn't work As Intended

### ISSUE THREAD

**Issue by ghost** [ohaiibuzzle/BuzzUtilityBot#4]
The Spotify parts doesn't work as expected unlike other music bots, and even in this regard is buggy.

## Expected Behavior
- Be able to play individual spotify songs 
- Play command should be able to judge whether or not something is a Spotify link or a Youtube link

## Current Behavior
- The Spotify command only seems to handle Spotify playlists, which is unideal
- The play command only manages YouTube links

## Steps to Reproduce
1. Use an individual track link for the spotify command instead of a palylist

1. Use the play command to play spotify links

## Detailed Description
A more intuitive play command that can handle both spotify links and youtube links would be ideal, reducing the possibility for user error. 
As well as allowing individual tracks to be played.

## Possible Implementation
Play command attempts to figure out what kind of link it is, before proceeding
Allow both playlists and individual tracks to be played.

**Comment by ghost** [comment]
I'm also considering reworking the error handling so it provides information to the users

**Comment by ohaiibuzzle** [comment]
Well, I was just super lazy (ehe) and implement just playlist because that is what I expect most to use.
Still, Spotify songs and album is now supported in both `.play` and `.spotify` by commit 6e4f89f43b7049cc8ad8f40a002a8303f44808d9

Regarding error handling, you probably don't want to print to Discord as this is the chaos you will eventually run into.
![image](https://user-images.githubusercontent.com/23693150/133354245-28bb6928-526f-4799-8486-019e9fcfe6e0.png)
...yeah, youtube-dl's errors ain't pretty

**Comment by ghost** [comment]
I'll figure out error handling, but thanks for the commit!

**Comment by ghost** [comment]
Oh and the commit is for a readme :p

**Comment by ohaiibuzzle** [comment]
Yeah I copied the wrong hash, fixed now, whoops :upside_down_face:
